"""Initial migration.

Revision ID: 04979bb4dcf0
Revises: 
Create Date: 2024-05-07 16:15:33.421721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04979bb4dcf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
